movie_site:
  imdb:
    url_base: 'https://www.imdb.com/'
    url: 'https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm'
    queries: 
      home_movie_links: '//tbody[@class="lister-list"]/tr//a[@href and @title]/@href'
      movie_title: '//div[@class="title_wrapper"]/h1/text()[1]'
      movie_year: '//div[@class="title_wrapper"]//span[@id="titleYear"]/a/text()'
      movie_gender: '//div[@class="title_wrapper"]/div[@class="subtext"]/a[not(@title)]/text()'
      movie_rating: '//div[@class="title_bar_wrapper"]//div[@class="ratingValue"]//span[@itemprop="ratingValue"]/text()'
      movie_director: '//div[@class="plot_summary_wrapper"]//div[@class="credit_summary_item"][1]/a/text()'
      movie_sumary: '//div[@class="plot_summary_wrapper"]//div[@class="summary_text"]/text()'
      movie_duration: '//div[@class="title_wrapper"]//time[@datetime]/text()'

  reelgood:
    url_base: 'https://reelgood.com/'
    url: 'https://reelgood.com/movies/browse/popular-movies'
    queries: 
      home_movie_links: '//tbody/tr[@class="css-o6sgwe"]//td/a[@href]/@href'
      movie_title: '//section[@class="css-vzt30e e14injhv0"]//h1[@class="css-of585f e14injhv7"]/text()'
      movie_year: '//div[@class="css-1avg5xn ey4ir3j0"]//span[@class="css-dpg6zk ey4ir3j1"][5]/a[@href]/text()'
      movie_gender: '//div[@class="css-1avg5xn ey4ir3j0"]//span[@class="css-dpg6zk ey4ir3j1"][3]/a[@href]/text()'
      movie_rating: '//div[@class="css-1avg5xn ey4ir3j0"]//span[@class="css-dpg6zk ey4ir3j1"][2]//span[@class="css-xmin1q ey4ir3j8"]/text()'
      movie_director: '//div[@class="css-1baulvz e1yfir8f5"]//a[@itemprop="director"]//h3/text()'
      movie_sumary: '//div[@class="css-zzy0ri e50tfam1"]//p[@itemprop="description"]/text()'
      movie_duration: '//div[@class="css-1avg5xn ey4ir3j0"]//span[@class="css-dpg6zk ey4ir3j1"][6]/text()'
